<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFrameworks>$(MinCoreTargetFramework);$(MinTargetFramework)</TargetFrameworks>
    <LangVersion>14.0</LangVersion>
    <RootNamespace>Snoop</RootNamespace>

    <UseWpf>true</UseWpf>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);PInvoke009</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\Artwork\*.ico" />

    <Content Include="Scripts\*.psm1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <_WpfCommonNetFxReference Remove="System.Windows.Controls.Ribbon" />
  </ItemGroup>

  <ItemGroup Label="PowerShell">
    <Reference Include="System.Configuration" Condition="'$(TargetFramework)' == '$(MinTargetFramework)'" />
    <PackageReference Include="microsoft.powershell.3.referenceassemblies" PrivateAssets="All" Condition="'$(TargetFramework)' == '$(MinTargetFramework)'" />

    <PackageReference Include="System.Management.Automation" PrivateAssets="All" Condition="'$(TargetFramework)' != '$(MinTargetFramework)'" />

    <PackageReference Include="Microsoft.Windows.CsWin32" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' != '$(MinTargetFramework)'">
    <DefineConstants>$(DefineConstants);USE_WPF_BINDING_DIAG</DefineConstants>
  </PropertyGroup>
</Project>